name: update_cf_regions_mapping

on:
  push:
  pull_request:
  schedule: 
      - cron: '1 6,20 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      name: Checkout Repository
    - name: Install jq
      run: sudo apt-get install jq
    - name: Fetch data and validate JSON
      run: |
            for i in {1..5}
            do 
                # Fetch data
                response=$(curl --write-out "%{http_code}" --silent --output src/routing.json "https://delay.cloudflare.chaika.me/v2/colos/iataregionr2")
                
                # Check response code
                if [ "$response" -ne 200 ]; then
                echo "Failed to fetch data, retrying in 5s. Retry: $i/5."
                sleep 5
                else
                # Validate JSON
                cat src/routing.json | jq empty > /dev/null 2>&1
                if [ "$?" -ne 0 ]; then
                    echo "Invalid JSON data, retrying in 5s. Retry: $i/5."
                    sleep 5
                else
                    echo "Successfully fetched and validated JSON data"
                    break
                fi
                fi

                # Failed after max retries
                if [ "$i" -eq 5 ]; then
                echo "Failed to fetch and validate data after $i attempts"
                exit 1
                fi
            done
    - name: Publish
      uses: cloudflare/wrangler-action@v3
      with:
            apiToken: ${{ secrets.CF_API_TOKEN_DEPLOY }}
            workingDirectory: ""
            wranglerVersion: "3"
  keepalive-job:
    name: Keepalive Workflow
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
